services:
  - type: web
    name: event-registration-api
    runtime: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: node config/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DB_SSL
        value: "true"
